bilaval:
  notes: [s, r, g, m, p, d, n]
  aroh: [s, r, g, m, g, r, g, p, d, n, s+]
  avroh: [s+, n, d, p, g, r, g, p, m, g, r, s]
  vadi: d
  samvadi: g
  info:
    thaat: bilaval
    jati: sampuran-sampuran

asa:
  notes: [s, r, g, m, p, d, n]
  aroh: [s, r, m, p, d, s+]
  avroh: [s+, n, d, p, m, g, r, s]
  aroh_varjit: [g, n]
  vadi: m
  samvadi: s
  info:
    thaat: bilaval
    jati: aurav-sampuran

bhairo:
  notes: [s, r., g, m, p, d., n]
  aroh: [s, r., g, m, p, d., n, s+]
  avroh: [s+, n, d., p, m, g, r., s]
  vadi: d.
  samvadi: r.
  info:
    thaat: bhairo
    jati: sampuran-sampuran

suhi:
  notes: [s, r, g, m, p, d, n., n]
  aroh: [s, r, g, m, p, n, d, n, s+]
  avroh: [s+, n., d, p, m, g, r, g, r, s]
  vadi: p
  samvadi: s
  info:
    thaat: bilaval
    jati: sampuran-sampuran

gond:
  notes: [s, r, g, m, p, d, n]
  aroh: [s, r, g, m, p, d, n, d, n, s+]
  avroh: [s+, n, d, n, p, m, g, r, s]
  vadi: s
  samvadi: m
  info:
    thaat: bilaval
    jati: sampuran-sampuran

sarang:
  notes: [s, r, m, p, n., n, s+]
  aroh: [s, r, m, p, n, s+]
  avroh: [s+, n., p, m, r, n, s]
  vadi: r
  samvadi: p
  info:
    thaat: kafi
    jati: aurav-aurav

kedara:
  notes: [s, r, m, m', d, n., n, s+]
  aroh: [s, m, p, m', p, d, n, s+]
  avroh: [s+, n, d, p, m', p, d, n., d, p, m', p, d, p, m, r, s]
  avroh: 
  vadi: m
  samvadi: s
  info:
    that: kalian
    jati: aurav-chaanav
  
